### ISSUE TITLE
Add a new constraint to the to_constant_volume method

### ISSUE THREAD

**Issue by Taarnborg** [benmaier/binpacking#6]
Hi there!

I'm looking for a way to use your `to_constant_volume` method with an additional constraint. I would like to add an option to constrain the number of elements a bin can hold.

So for instance, each bin should have no more than 50 elements and the total weight of each bin should not exceed 1500. 

Is that an easy thing to implement into your method? 

I have no experience with bin packing, and I just happend to find your module when looking for a way to repack a bunch of api calls.

Any help would be appreciated.

Ronnie

**Comment by benmaier** [comment]
interesting! But I don't think it's a trivial problem which can be solved by easily adjusting my code. I've found [this on StackOverflow](https://stackoverflow.com/questions/48866506/binpacking-multiple-constraints-weightvolume), maybe it's of help?

**Comment by Taarnborg** [comment]
Thanks for the link! 

I ended up with a simple solution that is sup-optimal, but work fine for my purpose. Basically I just open up a bin, and start filling it with the elements from an ordered list that gets reversed after each iteration. If the first element of the list fits the criteria, it goes in the bin and is then deleted from the list. If the element does not fit the criteria, the process is repeated with the reversed list. If this also fails (i.e. we have two successive fails), the bin is closed. This process then gets repeated until the list is empty. 

This leaves me with a bunch of bins that are not filled to their max capacity, because I use up the small elements quickly, and is then forced to pack medium sized elements together.

Anyway, should I close the issue?

**Comment by benmaier** [comment]
I see. Your solution is a bit the other way around from the best-fit heuristic which is implemented here. I don't know if that helps but in the best-fit heuristic, a list of items is sorted decreasingly by their weight. This list is then iterated. For each element, the best bin is searched, where _best_ refers to the _fullest_ bin which can still fit this item. For your problem you have to redefine what _fullest_ means, which would probably be some mixture of the space it has for the weights as well as the number of items and can still hold. This redefinition kind of depends on what you want to optimize: do you want a minimal number of bins or do you want equal distribution of item numbers?

I'm closing this now, because I won't implement it in the package.

**Comment by Taarnborg** [comment]
Ah, I see. It totally makes sense to have multiple bins open at the same time, and then search for the best bin. I hadn't thought about doing that, so thanks for the input on best-fit heuristic. 😃

**Comment by abubelinha** [comment]
First of all, thanks a lot for this nice package!

My use case is not exactly the same as @Taarnborg , but it is similar.
I would like the number of bin elements to be more equally distributed.
The following example is not exactly my case but it well illustrates the problem:

Let's say I want to group 500 people in buses so their summed weights do not exceed 4000 Kg per bus.
Each bus has a limited number of seats (say 50, so that's an average of 80 Kg/person if all seats are used).

We don't want all heavy people to travel in just a couple of buses with so many empty seats, and all small children to be packed without adults in the last buses (probably before reaching 2000 Kg all seats in the bus would be already occupied).  
So a more distributed number of items would be a better solution here.

Just another example of the interest of this issue.  
@abubelinha
